### PR TITLE
Drop changes needed for 0.4.18 and update a few other things

### PR DESCRIPTION
**Pull request by jaimergp**
For the 0.4.18 release we had to ignore some settings from upstream, namely:

- Disabled `osx-arm64` installers
- Out-of-date `napari-menu-config.json` (pending https://github.com/napari/napari/pull/6056)

I am reverting these changes now, and also updating the installers to have:

- Python 3.9 on Windows (for consistency with the other platforms)
- Adding `napari-plugin-manager` as a dependency in the bundle

### CODE REVIEW

**Comment by Czaki** [comment]
We will do 0.4.19 is sort time so maybe wait a moment with this PR.

**Comment by jaimergp** [comment]
Does 0.4.19 have its own napari-plugin-manager?

**Comment by jaimergp** [comment]
Got it, I'll wait then! Thanks!

**Comment by jaimergp** [comment]
0.4.19 landed so we can start merging these!

**Pull request merged**
