### PR TITLE
Update installer infra to catch up with upstream (part two)

### PR DESCRIPTION
**Pull request by jaimergp**
Continues work started in #42, part of #15

### CODE REVIEW

**Comment by jaimergp** [comment]
Updates to `bundle_tools_2` complete.

**Comment by jaimergp** [comment]
Most of the changes involved in this new series didn't happen in this feedstock, but in other repos as mentioned in https://github.com/napari/packaging/issues/15#issuecomment-1302638556

Summary of changes:

- Support for MacOS permission system
- Support for elevation on Windows
- Find `base_prefix` more robustly
- Add `python` interface to conda-standalone

**Review by potating-potato — APPROVED** [review]

**Comment by jaimergp** [comment]
Thanks.

Note we changed how notarization works because the tool we were using (`altool`) is going to be [deprecated by Apple ](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow/notarizing_apps_when_developing_with_xcode_12_and_earlier)and the actions we used are now [archived and unmaintained](https://github.com/devbotsxyz/xcode-notarize). Fun fact: this was reported by the Anaconda team working on using our `constructor` improvements :)

This should be more reliable, but we need to test it in a run where the secrets are available.

So yes, let's merge to not block QA but I might need to adjust a couple details in a further PR.

**Comment by Carreau** [comment]
Is there anything I ca do to help test this ? In particular I have a mac with an apple arm64 chip if that helps.

**Comment by jaimergp** [comment]
We need to check the notarization steps, running here https://github.com/napari/napari/pull/5411

Once we have some artifacts, we can QA whether the installer throws warnings, shortcuts are created, etc. I'll ping you in the other PR once they are ready, @Carreau. Thanks!

**Pull request merged**
